# Generated by Django 4.2.6 on 2023-10-13 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_addressrating_is_default_roommaterating_is_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roommate",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.address",
            ),
        ),
    ]
